name: Daily Market Email

on:
  schedule:
    - cron: '0 13 * * *'
  workflow_dispatch:

jobs:
  send-email:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install packages
        run: pip install -r requirements.txt

      - name: Run script
        env:
          EMAIL_USER: ${{ secrets.EMAIL_USER }}
          EMAIL_PASS: ${{ secrets.EMAIL_PASS }}
        run: python market_email.py
